In [30]:
import numpy as np
import matplotlib.pyplot as plt
import random

n=3
array = np.arange(n*3.0).reshape(n,3)   

for i in range(0,n):
    for j in range(0,3):
        array[i][j] = random.random()

def WhiteWash(x):
    print ("before whitewash")
    print (x)
    for i in range(0,n):
        for j in range(0,3):
            x[i][j] = (x[i][j]+1)/2
    print ("after whitewash")
    print (x)        
    return
WhiteWash(array)


before whitewash
[[ 0.85681128  0.04609223  0.8799532 ]
 [ 0.85774173  0.7577921   0.08168001]
 [ 0.31882183  0.20742235  0.07962243]]
after whitewash
[[ 0.92840564  0.52304611  0.9399766 ]
 [ 0.92887087  0.87889605  0.54084001]
 [ 0.65941091  0.60371118  0.53981121]]
